### ISSUE TITLE
Phantoms aren't controllable

### ISSUE THREAD

**Issue by cda94581** [cda94581/Community_Collabs#27]
After leaving the ground, you can't get back down.
Steps to reproduce:
2 Methods:
- Method 1: Morph into a Phantom and Jump
- Method 2: Morph into a Phantom and walk off a ledge

Expected result: You should be able to control your movement and move up, down, forward, backwards, etc.
Actual result: You lose control and if you jumped, will move upwards forever until you morph into another entity.

Temporary Fix in 0.0.2

Suggested fixes:
- [`/ability mayfly`](https://github.com/cda94581/Community_Collabs/issues/27#issuecomment-808840748)
- [`/effect @s feather_falling`](https://github.com/cda94581/Community_Collabs/issues/27#issuecomment-808840748)

Progress Fix in 0.0.4

**Comment by Hidden-Trial** [comment]
Hello, 
I had a look at your code so far. It looks promising at the moment. Regarding the Phantom, why don't you consider the following:

- Option 1: You can modify your Phantom item file. Add this "/ability @s mayfly true" to your run command event string. Remember to add the "/ability @s mayfly false" to all your other item file lines. Off the top of my head, you would have to enable the additional modding capabilities since I do believe the in-game 'ability command' is from Minecraft education edition and ported over. This option would allow the player to control their forward, backward, right/left and height position at will.       

- Option 2: In your phantom item file, apply an effect of feather falling in your run command event string. For example, "effect @s feather falling 1000000 1 true. Although, do make sure that you clear it for all other non-flying mobs. Secondly using the same idea, tag the player and use a filter component that is only looking for the 'allow_fly' tag. Test if the animation is crouching and give it a spell cast of 'levitation' for a couple of seconds. This would allow the player to 'hover' in place for a while. 

Best wishes,
Hidden

**Comment by cda94581** [comment]
Hey Hidden, these are great ideas! Once I begin to tackle this (soon maybe?), I'll be sure to keep these ideas in mind.

Hope you have a great day, and thanks for the ideas!

**Comment by cda94581** [comment]
Project moved to [new repository](https://github.com/cda94581/cdas-morph)
