### ISSUE TITLE
Chunk loader block doesn't activate in Nether or The End

### ISSUE THREAD

**Issue by Gengar-lab** [cda94581/Community_Collabs#82]
If you try to jump on Chunk loader block in dimension **other than Overworld**, it _doesn't get activated_.

I was able to chunk load other dimensions by spawning it with command ```/summon cda001:chunk_loader```.

cda94581's note: Fixed in 1.0.2.

**Comment by cda94581** [comment]
The pack uses `tick.json` as a way of being able to run `/execute detect` on a player, without modifying the player files, which makes for better compatibility with other packs.

However, the command configuration used appears to fail to work in the Nether or the End. Testing with running a `/say` command works fine in all dimensions. Testing with `/execute @e ~~~ say test` also works fine. However, running `/execute @e ~~~ detect ~~-1~ stone 0 say test` fails to work in other dimensions. Based on this, I can conclude that running an `execute/detect` command doesn't work, however the reason is unknown.

A few ideas as to a workaround for this:
- Embrace `player.json` and animations. Potentially release 2 separate packs, one that works in multiple dimensions but is possibly incompatible, and another that only works in the Overworld.
- Use renamed armor stands. That poses the issues that a) other armor stand tweaking packs won't work, and b) there should be a high cost for the chunk loader, which the armor stand would to bypass.
- Use a spawn egg. The problem with this is that if the egg was obtainable in survival, it could be placed into a spawner to create infinitely many, again defeating the purpose of making the chunk loader hard to obtain. I would definitely love to look into ways to make that impossible, but I have no idea as to whether or not I can do that.
- Use experimental blocks/items. My goal is to refrain from this, however if necessary, then using block triggers like `on_step_on` or `on_interact` might be a good idea. Item components might involve `on_use`.

**Comment by cda94581** [comment]
Undergoing more testing, `execute @a ~~~ detect` will fail, however running `execute @a ~~~ execute @s ~~~ detect` will succeed. Utilizing this will fix the issue, and an update will be pushed, addressing this.

Fixed in 1.0.2.
